"""
TensorVizion ComfyUI Nodes
load_image_with_metadata_node.py — A LoadImage-equivalent (delegates the
actual pixel/mask decoding to ComfyUI's own core LoadImage, not
reimplemented) with a real twist: it also RECOVERS the original
generation parameters embedded in the file, if any exist, and exposes
them as individually-wireable outputs — not just a dumped text blob the
way Metadata Reader (Model Nodes) does.

Drag in ANY finished PNG — your own past output, or someone else's
shared render — and if it has embedded generation data (from either
ComfyUI itself or an A1111/Forge-family UI), this node hands you back a
real seed INT you can wire into Seed Stepper, a real prompt STRING you
can wire into CLIPTextEncode, and the sampler/steps/cfg it was made
with, instead of a paragraph of text you'd have to read and retype by
hand.
"""

import json
import re

from nodes import LoadImage as _CoreLoadImage
import folder_paths


class LoadImageWithMetadataNode:
    """
    `source` selects which metadata format to look for:
      auto        — tries ComfyUI's own embedded workflow first, then
                     falls back to A1111/Forge-style "parameters" text.
      comfyui      — only looks for ComfyUI's own embedded "prompt" JSON
                     (the API-format graph ComfyUI embeds in every PNG
                     it saves, unless metadata embedding is disabled).
      a1111        — only looks for the A1111/Forge-style "parameters"
                     text chunk (also used by many A1111-compatible UIs).

    If no embedded metadata is found (or the file was never generated by
    either tool — a photo, a hand-drawn image, a render from an
    unsupported tool), `metadata_found` is False and the text/numeric
    outputs return sensible empty/zero defaults rather than raising —
    the image still loads normally either way.

    For the ComfyUI source: since an embedded workflow can contain
    MULTIPLE CLIPTextEncode/KSampler/checkpoint-loader nodes (e.g. a
    base+refiner workflow, or one with several prompt nodes), this
    node takes the FIRST KSampler-family node it finds for
    seed/steps/cfg/sampler, and separately picks the CLIPTextEncode
    node with the LONGEST text as the likely positive prompt and the
    shortest as the likely negative — a heuristic, not a guarantee, for
    workflows that don't follow a simple single-KSampler structure.
    """

    CATEGORY = "TensorVizion/Image"

    @classmethod
    def INPUT_TYPES(cls):
        input_dir = folder_paths.get_input_directory()
        import os
        files = [f for f in os.listdir(input_dir) if os.path.isfile(os.path.join(input_dir, f))]
        return {
            "required": {
                "image": (sorted(files), {"image_upload": True}),
                "source": (["auto", "comfyui", "a1111"],),
            }
        }

    RETURN_TYPES = ("IMAGE", "MASK", "BOOLEAN", "STRING", "STRING", "INT", "INT", "FLOAT", "STRING", "STRING")
    RETURN_NAMES = ("image", "mask", "metadata_found", "positive_prompt", "negative_prompt",
                     "seed", "steps", "cfg", "sampler_name", "checkpoint_name")
    FUNCTION = "run"

    # ------------------------------------------------------------------
    def _parse_a1111(self, text):
        if not text:
            return None

        # The params line is the block starting at "Steps:" — locate it
        # first since everything before it is prompt text (positive,
        # optionally followed by a negative-prompt section).
        params_match = re.search(r"Steps:\s*\d+.*", text, re.DOTALL)
        prompt_section = text[:params_match.start()] if params_match else text
        params_str = params_match.group(0) if params_match else ""

        neg_split = re.split(r"\nNegative prompt:\s*", prompt_section, maxsplit=1)
        positive = neg_split[0].strip()
        negative = neg_split[1].strip() if len(neg_split) > 1 else ""

        def _find(pattern, cast=str, default=None):
            m = re.search(pattern, params_str)
            if not m:
                return default
            try:
                return cast(m.group(1))
            except (ValueError, TypeError):
                return default

        seed = _find(r"Seed:\s*(\d+)", int, 0)
        steps = _find(r"Steps:\s*(\d+)", int, 0)
        cfg = _find(r"CFG scale:\s*([\d.]+)", float, 0.0)
        sampler = _find(r"Sampler:\s*([^,]+)", str, "")
        model = _find(r"Model:\s*([^,]+)", str, "")

        return {
            "positive": positive, "negative": negative,
            "seed": seed, "steps": steps, "cfg": cfg,
            "sampler_name": sampler.strip() if sampler else "",
            "checkpoint_name": model.strip() if model else "",
        }

    def _parse_comfyui(self, prompt_json_str):
        if not prompt_json_str:
            return None
        try:
            graph = json.loads(prompt_json_str)
        except json.JSONDecodeError:
            return None

        sampler_node = None
        checkpoint_name = ""
        text_candidates = []

        for node_id, node in graph.items():
            if not isinstance(node, dict):
                continue
            class_type = node.get("class_type", "")
            inputs = node.get("inputs", {})

            if sampler_node is None and "KSampler" in class_type:
                sampler_node = inputs
            if class_type == "CheckpointLoaderSimple" and "ckpt_name" in inputs:
                checkpoint_name = inputs["ckpt_name"]
            if class_type == "CLIPTextEncode" and isinstance(inputs.get("text"), str):
                text_candidates.append(inputs["text"])

        if sampler_node is None and not text_candidates and not checkpoint_name:
            return None

        positive, negative = "", ""
        if text_candidates:
            sorted_texts = sorted(text_candidates, key=len, reverse=True)
            positive = sorted_texts[0]
            negative = sorted_texts[-1] if len(sorted_texts) > 1 else ""

        seed = sampler_node.get("seed", sampler_node.get("noise_seed", 0)) if sampler_node else 0
        steps = sampler_node.get("steps", 0) if sampler_node else 0
        cfg = sampler_node.get("cfg", 0.0) if sampler_node else 0.0
        sampler_name = sampler_node.get("sampler_name", "") if sampler_node else ""

        return {
            "positive": positive, "negative": negative,
            "seed": int(seed) if isinstance(seed, (int, float)) else 0,
            "steps": int(steps) if isinstance(steps, (int, float)) else 0,
            "cfg": float(cfg) if isinstance(cfg, (int, float)) else 0.0,
            "sampler_name": sampler_name,
            "checkpoint_name": checkpoint_name,
        }

    def run(self, image, source):
        loader = _CoreLoadImage()
        loader_fn = getattr(loader, loader.FUNCTION)
        image_tensor, mask_tensor = loader_fn(image)[:2]

        image_path = folder_paths.get_annotated_filepath(image)
        from PIL import Image as PILImage
        pil_info = {}
        try:
            with PILImage.open(image_path) as pil_img:
                pil_info = dict(pil_img.info) if hasattr(pil_img, "info") else {}
        except Exception:
            pil_info = {}

        parsed = None
        if source in ("auto", "comfyui"):
            parsed = self._parse_comfyui(pil_info.get("prompt"))
        if parsed is None and source in ("auto", "a1111"):
            parsed = self._parse_a1111(pil_info.get("parameters"))

        if parsed is None:
            return (image_tensor, mask_tensor, False, "", "", 0, 0, 0.0, "", "")

        return (
            image_tensor, mask_tensor, True,
            parsed["positive"], parsed["negative"],
            parsed["seed"], parsed["steps"], parsed["cfg"],
            parsed["sampler_name"], parsed["checkpoint_name"],
        )


NODE_CLASS_MAPPINGS = {
    "LoadImageWithMetadataNode": LoadImageWithMetadataNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "LoadImageWithMetadataNode": "Load Image + Recovered Metadata 🔍",
}
